# Use postgres/example user/password credentials

services:

  db:
    volumes:
      - ./resources/:/docker-entrypoint-initdb.d/
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres  # ✅ Ensure init scripts run against the correct DB
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
