@SERVER=localhost
@PORT=8080
@BASE_URL=http://{{SERVER}}:{{PORT}}
### ============ ENDPOINTS ============
### Listar todos los usuarios
GET {{BASE_URL}}/users HTTP/1.1

### Usar parámetro de consulta para limitar cantidad de resultados
GET {{BASE_URL}}/users?limit=2&offset=2 HTTP/1.1

### Listar todos los productos
GET {{BASE_URL}}/api/products HTTP/1.1

### Listar todos los usuarios
GET {{BASE_URL}}/users HTTP/1.1
### Listar todos los deliveries
GET {{BASE_URL}}/delivery HTTP/1.1
### Listar todos los carritos
GET {{BASE_URL}}/api/cart HTTP/1.1
### Listar los carritos de un usuario específico
GET {{BASE_URL}}/api/cart/user/1 HTTP/1.1

### Crear nuevo producto
POST {{BASE_URL}}/api/products HTTP/1.1
Content-Type: application/json

{
  "productId": 10,
  "name": "Hulk",
  "description": "SMASH!",
  "price": 120000
}

### Crear nuevo usuario
POST {{BASE_URL}}/users HTTP/1.1
Content-Type: application/json

{
  "username": "Rubia69",
  "name": "Kakaroto Vegito",
  "address": "Some Address 102401 A 20 20, Some City",
  "email": "vicioso48@yahoo.com",
  "password": "dickXXX69",
  "roleId": 2
}

### Crear nuevo delivery
POST {{BASE_URL}}/delivery HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "address": "Carrera 50X 70 61, Prado, Medellín",
  "zipCode": 50032,
  "phoneNumber": "3154129040"
}
### Crear nuevo carrito
POST {{BASE_URL}}/api/cart HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 3
    },
    {
      "productId": 3,
      "quantity": 5
    }
  ]
}
### Actualizar un producto existente
PUT {{BASE_URL}}/api/products/10 HTTP/1.1
Content-Type: application/json

{
  "description": "SMASHED AND UPDATED!",
  "price": "50000"
}
### Actualizar un usuario existente
PUT {{BASE_URL}}/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Gaygaroto Vegito"
}
### Actualizar un delivery existente
PUT {{BASE_URL}}/delivery/1 HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "address": "Carrera 50X 70 61, ACTUALIZADO, Medellín",
  "phoneNumber": "3104129040"
}
### Actualizar un carrito existente
PUT {{BASE_URL}}/api/cart/6 HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "items": [
    {
      "productId": 4,
      "quantity": 1
    }
  ]
}
### Eliminar un producto existente
DELETE {{BASE_URL}}/api/products/10 HTTP/1.1
### Eliminar un producto existente
DELETE {{BASE_URL}}/users/5 HTTP/1.1
### Eliminar un delivery existente
DELETE {{BASE_URL}}/delivery/1 HTTP/1.1
### Eliminar un carrito existente
DELETE {{BASE_URL}}/api/cart/7 HTTP/1.1
